module.exports = {
  purge: {
    content: [
      'app/templates/**/*.html',
      'app/static/js/core.js',
      'app/static/js/edit.js',
      'app/static/js/ratings.js',
    ],
    enabled: true,
    options: {
      safelist: [
        'hidden',
        'hover:opacity-70',
        'hover:opacity-80',
        'hover:underline',
        'hover:bg-red-700',
        'lg:flex-row',
        'lg:w-5/12',
        'lg:w-7/12',
      ],
    } 
  },
  theme: {
    extend: {
      spacing: {
        '0.75': '3px',
        '2.5': '10px',
        '3.5': '14px',
        '4.5': '18px',
        '11': '44px',
      },
      fontSize: {
        'xxs': ['10px', { lineHeight: '1.2' }],
        '2xs': ['11px', { lineHeight: '1.3' }],
        'sm-': ['13px', { lineHeight: '1.4' }],
        'base-': ['15px', { lineHeight: '1.5' }],
      },
      borderWidth: {
        '3': '3px',
      },
      colors: {
        // background colors
        "primary-bg": "var(--bg-primary)",
        "secondary-bg": "var(--bg-secondary)",
        "album-header-bg": "var(--album-header-bg)",
        "navbar-bg": "var(--navbar-bg)",
        "header-row": "var(--header-row)",
        "key-bg-standard": "var(--key-bg-standard)",
        "key-bg-stealth": "var(--key-bg-stealth)",
        "header-user-bg": "var(--header-user-bg)",
        "search-bg": "var(--search-section-bg)",
        "hover-bg": "var(--hover-bg)",
        "discography-bg": "var(--discography-background)",
        "duplicate-tag-bg": "var(--duplicate-tag-bg)",
        // text colors
        "primary-text": "var(--text-primary)",
        "secondary-text": "var(--text-secondary)",
        "navbar-text": "var(--navbar-text)",
        "artist-button-text": "var(--artist-button-text)",
        "search-text": "var(--search-section-text)",
        "button-text": "var(--button-text)",
        "discography-text": "var(--discography-text)",
        "duplicate-tag-text": "var(--duplicate-tag-text)",
        // buttons,, tables & misc
        "album-name": "var(--album-name)",
        "link": "var(--link)",
        "button-primary": "var(--button-primary)",
        "button-secondary": "var(--button-secondary)",
        "border": "var(--border)",
        "promoted": "var(--promoted-song)",
        "male": "var(--gender-male)",
        "female": "var(--gender-female)",
        "mixed-gender": "var(--gender-mixed)",
        "anime": "var(--gender-anime)",
        "row-alternate": "var(--row-alternate)",
        "grid-line": "var(--grid-line)",
        "delete": "var(--delete-button)",
        "edit-on": "var(--edit-on-button)",
        "edit-off": "var(--edit-off-button)",
        "navbar-active": "var(--navbar-active)",
        // rating-related colors
        "rating-5-bg": "var(--rating-5-bg)",
        "rating-4-bg": "var(--rating-4-bg)",
        "rating-3-bg": "var(--rating-3-bg)",
        "rating-2-bg": "var(--rating-2-bg)",
        "rating-1-bg": "var(--rating-1-bg)",
        "rating-0-bg": "var(--rating-0-bg)",
        "rating-5-text": "var(--rating-5-text)",
        "rating-4-text": "var(--rating-4-text)",
        "rating-3-text": "var(--rating-3-text)",
        "rating-2-text": "var(--rating-2-text)",
        "rating-1-text": "var(--rating-1-text)",
        "rating-0-text": "var(--rating-0-text)",
        "heatmap-high": "var(--heatmap-high)",
        "heatmap-mid": "var(--heatmap-mid)",
        "heatmap-low": "var(--heatmap-low)",
        "pct-high": "var(--pct-high)",
        "pct-mid": "var(--pct-mid)",
        "pct-low": "var(--pct-low)",
        "unrated-bg": "var(--unrated-0-bg)",
        "unrated-low-bg": "var(--unrated-low-bg)",
        "unrated-mid-bg": "var(--unrated-mid-bg)",
        "unrated-high-bg": "var(--unrated-high-bg)",
        "unrated-text": "var(--unrated-text)",
        // update and submission colors
        "feature": "var(--update-type-feature)",
        "bugfix": "var(--update-type-bugfix)",
        "style": "var(--update-type-style)",
        "perf": "var(--update-type-perf)",
        "code": "var(--update-type-code)",
        "submission-artist": "var(--submission-type-artist)",
        "submission-album": "var(--submission-type-album)",
        "submission-song": "var(--submission-type-song)",
        "submission-rating": "var(--submission-type-rating)",
        "submission-note": "var(--submission-type-note)",
      }
    }
  }
}